name: dotnet build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mod-version: ['v1.2', 'v1.3', 'v1.4', 'v1.5', 'v1.6']

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore ./Source/InGameWiki/InGameWiki.csproj

      - name: Build
        run: dotnet build ./Source/InGameWiki/InGameWiki.csproj -c ${{ matrix.mod-version }}

