name: Build-on-push CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0.x'
    - name: Install dependencies
      run: dotnet restore ./Source/InGameWiki/InGameWiki.csproj
    - name: Build
      run: dotnet build ./Source/InGameWiki/InGameWiki.csproj --configuration Release --no-restore
